notifications:
  email: false
dist: xenial
language: cpp
os: linux
compiler:
- clang
cache: ccache
before_install:
- docker pull doscode/merger-build-env:1.0
- docker run -i -t --name build-env merger-build-env:1.0 /bin/bash
install:
script:
- |
  cd lib/leveldb
  mkdir -p build
  cd build
  cmake -DCMAKE_BUILD_TYPE=Release ..
  cmake --build .
  cd ../../../
- |
- mkdir -p build && cd build
- cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER="clang++" ..
- cp ../scripts/run-clang-tidy.py run-clang-tidy.py
- pip3 install wheel
- pip3 install pyyaml
- python3 run-clang-tidy.py > lint_output.txt
- |
  if [[ -n $(grep "warning: " lint_output.txt) ]] || [[ -n $(grep "error: " lint_output.txt) ]]; then

    echo "You must pass the clang tidy checks before submitting a pull request"
    echo ""
    grep --color -E '^|warning: |error: ' lint_output.txt
    exit -1;
  else
    echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
  fi
- ls
- cmake --build .
- ctest --verbose
