dist: xenial
language: cpp
os: linux
compiler:
- clang

before_install:
- sudo apt-get update
install:
- sudo apt-get install -y python3-pip
#  boost
- sudo apt-get install -y libboost-all-dev
- pip3 install cmake
- |
  if [[ -z $(ls | grep grpc) ]]; then
    git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
  fi
- |
  if [[ -z $(ls | grep cryptopp) ]]; then
      git clone https://github.com/weidai11/cryptopp.git
  fi
- |
  if [[ -z $(ls | grep lz4) ]]; then
    git clone https://github.com/lz4/lz4.git
  fi
script:
- cd lz4 && sudo make install && cd ..
- cd lib/leveldb && mkdir -p build && cd build
- ls
- cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && cd ../../../
- cd grpc && git submodule update --init && sudo make && sudo make install && cd third_party/protobuf && sudo make install && cd ../../..
- |
  cd cryptopp
  git submodule add https://github.com/noloader/cryptopp-cmake.git cmake
  git submodule update --remote
  cp "$PWD/cmake/cryptopp-config.cmake" "$PWD"
  cp "$PWD/cmake/CMakeLists.txt" "$PWD"

  cmake . && cmake --build .
  make install
  cd ..
- mkdir -p build && cd build
- cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER="clang++-6.0" ..
- cp ../scripts/run-clang-tidy.py run-clang-tidy.py
- pip3 install pyyaml
- python3 run-clang-tidy.py > lint_output.txt
- |
  if [[ -n $(grep "warning: " lint_output.txt) ]] || [[ -n $(grep "error: " lint_output.txt) ]]; then

    echo "You must pass the clang tidy checks before submitting a pull request"
    echo ""
    grep --color -E '^|warning: |error: ' lint_output.txt
    exit -1;
  else
    echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
  fi
- cmake --build .
- ctest > test_output.txt
- |
  if [[ -n $(grep "warning: " test_ouput.txt) ]] || [[ -n $(grep "error: " test_output.txt) ]]; then
    echo "You must pass tests, checks before submitting a pull request"
    echo ""
    grep --color -E '^|warning: |error: ' test_output.txt
    exit -1;
  else
    echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
  fi